<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Python &#43;Selenium 自学笔记（第八天） - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="Python &#43;Selenium 自学笔记（第八天）" />
<meta property="og:description" content="认识异常 Python用异常对象（Exception Object）来表示异常情况，在遇到错误后，异常对象会引发异常，如果异常对象并未被处理过被捕捉到程序责会利用回溯（Trackback）一种错误现象来终止程序 open(&#34;text.txt&#34;,&#39;r&#39;) 我们通过open方法以只读的形式打开一个文件然后pyhon抛出一个FileNotFoundError类型的异常，他告诉我们No such file or directory :&#34;test.txt&#34; 没有test.txt这样的文件或目录 因为我们没有创建这样的文件所有才才找不到 既然我们知道打开一个不存在的文件时Pyhon会抛出一个 FileNotFoundError，按我我们可以通过Python提供的 try except 语句来捕捉并处理这个异常 创建test.py文件并写出一下代码 try : open(&#34;abc.txt&#34;,&#39;r&#39;) except FileNotFoundError print(&#34;异常了啊&#34;) 再次运行程序因为 try except 捕捉到FileNotfoundError 异常 所以会打印）（异常了啊） 再次修改程序，使其打印一个没有定义的比变量a try : print(a) except FileNotFoundError print(&#34;异常了啊&#34;) 我们不是已经通过 try except 来接收异常信息了吗为什么还是会报错呢，细品就会发现这次的错误是 NameError类型的错误而FileNotFoundError 只能接收找不到文件类型的错误 驴唇不对马嘴的意思 这里我们只需要将异常的类型改为NameError就可以了 try : print(a) except NameError : print(&#34;异常了啦&#34;) 知识延伸:异常的抛出机制 1.如果在程序运行中发生异常，那么解释器会查找相应的处理语句称为（handler） 2.如果在当前函数里没有找到相应的处理语句，那么解释器会将异常传递给上层的调用函数，看看上层函数能否处理 3.如过在最外层函数全局函数main() 也没有找到，那么解释器会退出，同时打印Traceback,以便让用户找到错误原因 注意：虽然大多数错误都会导致异常，但异常也不一定代表错误，有时候他们只是个警告，有时候是个终止信号，如退出循环等 在Python中，所有的异常类都继承自Exception 但自pyhon2.5后所有的异常类就有了新类BaseException，Exception同样也继承与BaseException 所以我们可以使用BaseException来接收所有类型的异常 try : print(a) open(&#34;adb.txt&#34;,&#39;r&#39;) except BaseException : print(&#34;异常了啦&#34;) 对于以上异常，BaseException就能捕捉到异常并打印异常了，但是我们不知道具体时间哪一行出现了异常 如何让Pyhon告诉我们是哪一行代码出现了错误 try : print(a) open(&#34;" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/4c6cf233bbf7c8dfdc6afa116b3b6d0a/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2019-12-24T16:29:30+08:00" />
<meta property="article:modified_time" content="2019-12-24T16:29:30+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Python &#43;Selenium 自学笔记（第八天）</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <div> 
 <span style="color:#333333;"><strong>认识异常</strong></span> 
</div> 
<div> 
 <span style="color:#333333;">Python用异常对象（Exception Object）来表示异常情况，在遇到错误后，异常对象会引发异常，如果异常对象并未被处理过被捕捉到程序责会利用回溯（Trackback）一种错误现象来终止程序</span> 
</div> 
<div> 
 <span style="color:#333333;">open("text.txt",'r')</span> 
</div> 
<div> 
 <span style="color:#333333;">我们通过open方法以只读的形式打开一个文件然后pyhon抛出一个FileNotFoundError类型的异常，他告诉我们No such file or directory :"test.txt" 没有test.txt这样的文件或目录</span> 
</div> 
<div> 
 <span style="color:#333333;">因为我们没有创建这样的文件所有才才找不到</span> 
</div> 
<div> 
 <span style="color:#333333;">既然我们知道打开一个不存在的文件时Pyhon会抛出一个</span> 
 <span style="color:#333333;">FileNotFoundError，按我我们可以通过Python提供的 try except 语句来捕捉并处理这个异常  </span> 
</div> 
<div> 
 <span style="color:#333333;">创建test.py文件并写出一下代码</span> 
</div> 
<div> 
 <span style="color:#7600d8;">try :    </span> 
</div> 
<div> 
 <span style="color:#7600d8;">    open("abc.txt",'r')</span> 
</div> 
<div> 
 <span style="color:#7600d8;">except </span> 
 <span style="color:#7600d8;">FileNotFoundError</span> 
</div> 
<div> 
 <span style="color:#7600d8;">    print("异常了啊")</span> 
</div> 
<div>
  再次运行程序因为 try except 捕捉到FileNotfoundError  异常 所以会打印）（异常了啊） 
</div> 
<div>
  再次修改程序，使其打印一个没有定义的比变量a 
</div> 
<div> 
 <span style="color:#8600a4;">try :</span> 
</div> 
<div> 
 <span style="color:#8600a4;">    print(a)</span> 
</div> 
<div> 
 <span style="color:#8600a4;">except FileNotFoundError</span> 
</div> 
<div> 
 <span style="color:#8600a4;">    print("异常了啊")</span> 
</div> 
<div>
  我们不是已经通过 try except 来接收异常信息了吗为什么还是会报错呢，细品就会发现这次的错误是 NameError类型的错误而FileNotFoundError 只能接收找不到文件类型的错误 驴唇不对马嘴的意思 这里我们只需要将异常的类型改为NameError就可以了 
</div> 
<div> 
 <span style="color:#4f009a;">try :</span> 
</div> 
<div> 
 <span style="color:#4f009a;">    print(a)</span> 
</div> 
<div> 
 <span style="color:#4f009a;">except NameError :</span> 
</div> 
<div> 
 <span style="color:#4f009a;">    print("异常了啦")</span> 
</div> 
<div>
    
</div> 
<div> 
 <strong>知识延伸:异常的抛出机制</strong> 
</div> 
<div>
  1.如果在程序运行中发生异常，那么解释器会查找相应的处理语句称为（handler） 
</div> 
<div>
  2.如果在当前函数里没有找到相应的处理语句，那么解释器会将异常传递给上层的调用函数，看看上层函数能否处理 
</div> 
<div>
  3.如过在最外层函数全局函数main() 也没有找到，那么解释器会退出，同时打印Traceback,以便让用户找到错误原因 
</div> 
<div> 
 <strong>注意：</strong>虽然大多数错误都会导致异常，但异常也不一定代表错误，有时候他们只是个警告，有时候是个终止信号，如退出循环等 
</div> 
<div>
  在Python中，所有的异常类都继承自Exception 但自pyhon2.5后所有的异常类就有了新类BaseException，Exception同样也继承与BaseException 所以我们可以使用BaseException来接收所有类型的异常 
</div> 
<div> 
 <span style="color:#4f009a;">try :</span> 
</div> 
<div> 
 <span style="color:#4f009a;">    print(a)</span> 
</div> 
<div> 
 <span style="color:#4f009a;">    open("adb.txt",'r')</span> 
</div> 
<div> 
 <span style="color:#4f009a;">except BaseException :</span> 
</div> 
<div> 
 <span style="color:#4f009a;">    print("异常了啦")</span> 
</div> 
<div>
  对于以上异常，BaseException就能捕捉到异常并打印异常了，但是我们不知道具体时间哪一行出现了异常 如何让Pyhon告诉我们是哪一行代码出现了错误 
</div> 
<div>
    
</div> 
<div style="margin-left:0px;"> 
 <span style="color:#4f009a;">try :</span> 
</div> 
<div style="margin-left:0px;"> 
 <span style="color:#4f009a;">    print(a)</span> 
</div> 
<div style="margin-left:0px;">
       
 <span style="color:#4f009a;">open("adb.txt",'r')</span> 
</div> 
<div style="margin-left:0px;"> 
 <span style="color:#4f009a;">except BaseException as mag :</span> 
</div> 
<div style="margin-left:0px;"> 
 <span style="color:#4f009a;">    print("异常")</span> 
</div> 
<div style="margin-left:0px;"> 
 <span style="color:#4f009a;">    print(mag)</span> 
</div> 
<div style="margin-left:0px;">
  我们在 BaseException 后面定义了一个msg 变量来接收异常信息，并通过 print()将其打印出来，运行结果如下 
</div> 
<div style="margin-left:0px;"> 
 <span style="color:#4f009a;">name 'a' is not defined</span> 
</div> 
<div style="margin-left:0px;">
    
</div> 
<div style="margin-left:0px;"> 
 <strong>Pyhon 中常见的异常</strong> 
</div> 
<div style="margin-left:0px;">
  BaseException  所有异常的基类 
</div> 
<div style="margin-left:0px;">
  Exception 所有异常的基类 但继承与BaseException  
</div> 
<div style="margin-left:0px;">
  AsscrtionError    assert语句失败 
</div> 
<div style="margin-left:0px;">
  FileNotFoundError    试图打开一个不存在的文件或目录 
</div> 
<div style="margin-left:0px;">
  AttribuleError    试图访问的对象没有属性 
</div> 
<div style="margin-left:0px;">
  OSEerror    当系统函数返回一个系统相关函数（包括I/O故障），如找不到文件或磁盘已满时引发此异常 
</div> 
<div style="margin-left:0px;">
  NameErro   使用一个未赋值的变量对象 
</div> 
<div style="margin-left:0px;">
  IndexError   当一个序列超出范围时引发此异常 
</div> 
<div style="margin-left:0px;">
  SyntaxError  当解析器遇到一个语法错误时引起的异常 
</div> 
<div style="margin-left:0px;">
  KeyboardInterrupt  当按下Ctrl+C，程序被强行终止 
</div> 
<div style="margin-left:0px;">
  TypeError  传入的对象类型与要求不符合 
</div> 
<div style="margin-left:0px;">
    
</div> 
<div style="margin-left:0px;">
  通过前面的学习我们了解到了一般的异常用法下面学习更多的异常用法 如 try except esle 用法 
</div> 
<div> 
 <span style="color:#9c004c;">try:</span> 
</div> 
<div> 
 <span style="color:#9c004c;">    a="异常测试"</span> 
</div> 
<div> 
 <span style="color:#9c004c;">    #a=input("请输入")</span> 
</div> 
<div> 
 <span style="color:#9c004c;">    print(a)</span> 
</div> 
<div> 
 <span style="color:#9c004c;">except NameError as msg:</span> 
</div> 
<div> 
 <span style="color:#9c004c;">    print(msg)</span> 
</div> 
<div> 
 <span style="color:#9c004c;">else :</span> 
</div> 
<div> 
 <span style="color:#9c004c;">    print("异常没有被执行")</span> 
</div> 
<div>
  这里我们对变量a进行了赋值，如果没有发生异常，则会执行else语句后的内容 
</div> 
<div>
    
</div> 
<div>
  有时候不管我们希望异常是否出现，有些操作都会执行，例如文件的关闭，锁的释放，把数据库的连接返回连接池等，我们可以使用try  except finally 实现这样的需求 
</div> 
<div> 
 <span style="color:#9c004c;">try :</span> 
</div> 
<div> 
 <span style="color:#9c004c;">    a="12"</span> 
</div> 
<div> 
 <span style="color:#9c004c;">    print(a)</span> 
</div> 
<div> 
 <span style="color:#9c004c;">except NameError as msg :</span> 
</div> 
<div> 
 <span style="color:#9c004c;">        print(msg)</span> 
</div> 
<div> 
 <span style="color:#9c004c;">finally :</span> 
</div> 
<div> 
 <span style="color:#9c004c;">    print("不管是否出现异常都会执行")</span> 
</div> 
<div>
  我们在给上面的a赋值以后再次运行验证finally语句是否被执行 
</div> 
<div>
    
</div> 
<div>
  如果你开发的是一个python的第三方库或框架，那么在程序运行时发生异常抛出异常现实的更为专业 在python中 raise关键字可用来抛出一个异常信息，下面的例子演示了raise的用法 
</div> 
<div style="margin-left:0px;"> 
 <div>
     
 </div> 
 <div>
   def sys_hello(name=None): 
 </div> 
</div> 
<div>
      if name is None: 
</div> 
<div>
          raise NameError("错了") 
</div> 
<div>
      else: 
</div> 
<div>
          print("hello %s" %name) 
</div> 
<div>
    
</div> 
<div>
  sys_hello() 
</div> 
<div>
  首先定义say_hello函数，设置参数name未None ,为函数中判断参数name如果未None，则抛出NanmeError提示（错了）否则打印hello 
</div> 
<div>
  需要注意的是raise只能使用pyhon提供的异常类，如果想要raise使用自定义类，则自定义类需要继承Exception类 
</div>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/beac8fa8bbe967f98288e73f1e6f7047/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">ios手机号和邮箱(支付宝账号)脱敏</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/378ae22dcc2ca579cc3d42961b1456df/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">SQL 数字和字符串互转</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>