<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>DoesNotExist: User matching query does not exist/ - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="DoesNotExist: User matching query does not exist/" />
<meta property="og:description" content="异常堆栈 File &#34;E:\python35\lib\site-packages\django\contrib\auth\decorators.py&#34;, line 21, in _wrapped_view return view_func(request, *args, **kwargs) File &#34;E:\pycharm\mysites\account\views.py&#34;, line 129, in myself_edit userprofile = UserProfiles.objects.get(user=request.user) if hasattr(request.user, &#39;userprofile&#39;) else UserProfile.objects.create(user=request.user) NameError: name &#39;UserProfile&#39; is not defined [04/Jan/2019 23:58:38] &#34;GET /account/edit-myinformation/ HTTP/1.1&#34; 500 72461 Internal Server Error: /account/myinformation/ Traceback (most recent call last): File &#34;E:\python35\lib\site-packages\django\db\backends\utils.py&#34;, line 85, in _execute return self.cursor.execute(sql, params) File &#34;E:\python35\lib\site-packages\django\db\backends\sqlite3\base.py&#34;, line 296, in execute return Database.Cursor.execute(self, query, params) sqlite3.IntegrityError: UNIQUE constraint failed: account_userprofiles." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/7686e7f6d32252ed2734ce6e982e53cc/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2019-01-03T22:59:02+08:00" />
<meta property="article:modified_time" content="2019-01-03T22:59:02+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">DoesNotExist: User matching query does not exist/</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>异常堆栈 </p> 
<pre class="has"><code class="language-python">File "E:\python35\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\pycharm\mysites\account\views.py", line 129, in myself_edit
    userprofile = UserProfiles.objects.get(user=request.user) if hasattr(request.user, 'userprofile') else UserProfile.objects.create(user=request.user)
NameError: name 'UserProfile' is not defined
[04/Jan/2019 23:58:38] "GET /account/edit-myinformation/ HTTP/1.1" 500 72461
Internal Server Error: /account/myinformation/
Traceback (most recent call last):
  File "E:\python35\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "E:\python35\lib\site-packages\django\db\backends\sqlite3\base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: account_userprofiles.user_id

The above exception was the direct cause of the following exception:
</code></pre> 
<pre class="has"><code class="language-python">  File "E:\python35\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "E:\python35\lib\site-packages\django\db\backends\sqlite3\base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: account_userprofiles.user_id
</code></pre> 
<p>异常堆栈 </p> 
<p>DoesNotExist: User matching query does not exist/</p> 
<pre class="has"><code class="language-python"> File "E:\pycharm\mysites\account\views.py", line 71, in myself
    userprofile = UserProfiles.objects.get(user=request.user)
  File "E:\python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\python35\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
account.models.UserProfiles.DoesNotExist: UserProfiles matching query does not exist.
</code></pre> 
<p>分析：</p> 
<p>当显示结果中不存在“值”时，会返回如标题的错误（DoesNotExist: User matching query does not exist.），程序终止运行。终止运行意味着后面的代码不再被执行，故而得不到自己想要的结果。</p> 
<p>Django docs define this clearly, I miss that, sorry</p> 
<blockquote> 
 <p>Storing additional information about users</p> 
 <p>If you'd like to store additional information related to your users, Django provides a method to specify a site-specific related model -- termed a "user profile" -- for this purpose.</p> 
 <p>To make use of this feature, define a model with fields for the additional information you'd like to store, or additional methods you'd like to have available, and also add a OneToOneField named user from your model to the User model. This will ensure only one instance of your model can be created for each User. For example:</p> 
 <pre class="has"><code>from django.contrib.auth.models import User

class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    accepted_eula = models.BooleanField()
    favorite_animal = models.CharField(max_length=20, default="Dragons.")
</code></pre> 
 <p>To indicate that this model is the user profile model for a given site, fill in the setting AUTH_PROFILE_MODULE with a string consisting of the following items, separated by a dot:</p> 
 <p>The name of the application (case sensitive) in which the user profile model is defined (in other words, the name which was passed to manage.py startapp to create the application). The name of the model (not case sensitive) class.</p> 
 <p>For example, if the profile model was a class named UserProfile and was defined inside an application named accounts, the appropriate setting would be:</p> 
 <pre class="has"><code>AUTH_PROFILE_MODULE = 'accounts.UserProfile'
</code></pre> 
 <p>When a user profile model has been defined and specified in this manner, each User object will have a method -- get_profile() -- which returns the instance of the user profile model associated with that User.</p> 
 <p>The method get_profile() does not create a profile if one does not exist. You need to register a handler for the User model's django.db.models.signals.post_save signal and, in the handler, if created is True, create the associated user profile:</p> 
 <h2>in models.py</h2> 
 <p>from django.contrib.auth.models import User from django.db.models.signals import post_save</p> 
 <pre class="has"><code># definition of UserProfile from above
# ...

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)</code></pre> 
</blockquote> 
<p> </p> 
<p><span style="color:#f67e15;">解决方法</span></p> 
<pre class="has"><code class="language-python">@login_required(login_url='account/login/')
def myself(request):
    user = User.objects.get(username=request.user.username)
    #userprofiles = UserProfiles.objects.get(user=user)
    #userinfo = UserInfo.objects.get(user=user)
    # userprofile = UserProfiles.objects.get(user=request.user)
    # userinfo = UserInfo.objects.get(user =request.user)
    userprofile = UserProfiles.objects.get(user=request.user) if hasattr(request.user,
                                                                        'userprofiles') else UserProfiles.objects.create(
        user=request.user)
    userinfo = UserInfo.objects.get(user=request.user) if hasattr(request.user,
                                                                  'userinfo') else UserInfo.objects.create(
        user=request.user)

    return render(request,'account/myself.html',{'user':user,'userinfo':userinfo,'userprofile':userprofile})

</code></pre> 
<p> </p> 
<p><span style="color:#f67e15;">解决方法</span></p> 
<p style="margin-left:0px;"><span style="color:#333333;">您确定该用户的UserProfile对象是否存在？Django不会自动为您创建它。</span></p> 
<p style="margin-left:0px;"><span style="color:#333333;">你可能想要的是这个：</span></p> 
<pre class="has" style="margin-left:0px;"><code class="language-hljs">u = User.objects.get(id=1）
zm = u.get_profile()
</code></pre> 
<h3>5 个解决方案</h3> 
<h4>#1</h4> 
<pre class="has"><code>try:
    user = UniversityDetails.objects.get(email=email)
except UniversityDetails.DoesNotExist:
    user = None
</code></pre> 
<p>I also see you're storing your passwords in plaintext (a big security no-no!). Why don't you use the built-in auth system?</p> 
<p>我还看到你将密码存储在明文(一个很大的安全禁忌!)你为什么不使用内置的自动签名系统呢?</p> 
<h4>#2</h4> 
<p>I also had this problem. It was caused by the development server not deleting the django session after a debug abort in Aptana, with subsequent database deletion. (Meaning the id of a non-existent database record was still present in the session the next time the development server started)</p> 
<p>我也有这个问题。这是由于开发服务器在Aptana中的调试中止之后没有删除django会话，并随后删除数据库而导致的。(意味着不存在的数据库记录的id在下一次开发服务器启动时仍然存在于会话中)</p> 
<p>To resolve this during development, I used</p> 
<p>为了在开发过程中解决这个问题，我使用了</p> 
<pre class="has"><code>request.session.flush()
</code></pre> 
<h4>#3</h4> 
<p>In case anybody is here and the other two solutions do not make the trick, check that what you are using to filter is what you expect:</p> 
<p>如果有人在这里，而其他两个解决方案没有达到这个目的，请检查您用来过滤的是您所期望的:</p> 
<pre class="has"><code>user = UniversityDetails.objects.get(email=email)
</code></pre> 
<p>is email a string, or a None? or an integer?</p> 
<p>电子邮件是字符串，还是没有?还是一个整数?</p> 
<h4>#4</h4> 
<p>You may try this way. just use a function to get your object</p> 
<p>你可以试试这种方法。只需使用一个函数来获取对象</p> 
<pre class="has"><code>def get_object(self, id):
    try:
        return UniversityDetails.objects.get(email__exact=email)
    except UniversityDetails.DoesNotExist:
        return False
</code></pre> 
<h4>#5</h4> 
<p>As mentioned in <a href="https://docs.djangoproject.com/en/dev/ref/models/querysets/#get" rel="nofollow">Django docs</a>, when <code>get</code> method finds no entry or finds multiple entries, it raises an exception, this is the expected behavior:</p> 
<p>如Django文档中所提到的，当get方法没有发现条目或发现多个条目时，它会引发异常，这是预期的行为:</p> 
<blockquote> 
 <p>get() raises MultipleObjectsReturned if more than one object was found. The MultipleObjectsReturned exception is an attribute of the model class.</p> 
 <p>如果发现了多个对象，那么get()将引发multipleobjectsreturn。multipleobjectsreturn异常是模型类的一个属性。</p> 
 <p>get() raises a DoesNotExist exception if an object wasn’t found for the given parameters. This exception is an attribute of the model class.</p> 
 <p>如果没有找到给定参数的对象，则引发一个DoesNotExist异常。这个异常是model类的一个属性。</p> 
</blockquote> 
<p>Using exceptions is a way to handle this problem, but I actually don't like the ugly <code>try-except</code> block. An alternative solution, and cleaner to me, is to use the combination of <code>filter</code> + <code>first</code>.</p> 
<p>使用异常是处理这个问题的一种方法，但实际上我不喜欢丑陋的try-except块。另一种解决方案，对我来说更干净，是先使用filter + first的组合。</p> 
<pre class="has"><code>user = UniversityDetails.objects.filter(email=email).first()
</code></pre> 
<p>When you do <code>.first()</code> to an empty queryset it returns <code>None</code>. This way you can have the same effect in a single line.</p> 
<p>当您执行.first()到空的queryset时，它将返回None。这样你就可以在一行中得到相同的效果。</p> 
<p>The only difference between catching the exception and using this method occurs when you have multiple entries, the former will raise an exception while the latter will set the first element, but as you are using <code>get</code> I may assume we won't fall on this situation.</p> 
<p>捕获异常和使用此方法的惟一区别是，当您有多个条目时，前者会引发异常，而后者将设置第一个元素，但是当您使用get时，我可能会认为我们不会陷入这种情况。</p> 
<p style="margin-left:0px;"><span style="color:#333333;">如果您确定该配置文件存在（并且您已正确设置AUTH_PROFILE_MODULE），则User模型已经有一个帮助方法来处理：</span></p> 
<p><br>  | </p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/93eb8bd4c1301bae27c4c85763bec601/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">SVM调参实例</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/553501ff870dd90d27ba7ad233aa3c4a/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">npm install http-server global 安装http-server服务器</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>